
default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock
  time_zone: 'Tokyo'

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: pawdo_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: pawdo_test

production:
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>
  database: pawdo_production
  username: pawdo
  password: <%= ENV["PAWDO_DATABASE_PASSWORD"] %>
